name: Monitoramento e Coleta Automática

on:
  schedule:
    - cron: '4 11 * * 1-5'   # Segunda a sexta 08:04 BRT (11:04 UTC)
    - cron: '4 15 * * 1-5'   # Segunda a sexta 12:04 BRT (15:04 UTC)
    - cron: '14 19 * * 1-5'  # Segunda a sexta 16:14 BRT (19:14 UTC)
    - cron: '4 23 * * 1-5'   # Segunda a sexta 20:04 BRT (23:04 UTC)
    - cron: '45 20 * * 5'    # Sexta-feira 17:45 BRT (20:45 UTC)
    - cron: '8 12 * * 6'     # Sábado 09:04 BRT (12:04 UTC)
    - cron: '4 15 * * 6'     # Sábado 12:04 BRT (15:04 UTC)
    - cron: '54 18 * * 6'    # Sábado 15:54 BRT (18:54 UTC)
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  monitoramento_coleta:
    runs-on: ubuntu-latest

    steps:
      - name: Iniciar Monitoramento (primeira vez)
        run: |
          echo "Iniciando o monitoramento..."
          curl -X GET http://198.58.120.71:8001/iniciar-monitoramento || echo "Monitoramento já iniciado."

      - name: Pausar Monitoramento 1 Minuto Antes
        run: |
          echo "Pausando monitoramento 1 minuto antes do horário..."
          curl -X GET http://198.58.120.71:8001/parar-monitoramento
          echo "Monitoramento pausado com sucesso."
          sleep 60

      - name: Executar Coleta (com Retry)
        run: |
          for i in {1..3}; do
            response=$(curl -s -o /dev/null -w "%{http_code}" -X POST http://198.58.120.71:8001/executar-coleta)
            if [ "$response" == "200" ]; then
              echo "Coleta executada com sucesso."
              exit 0
            fi
            echo "Tentativa $i falhou. Retentando em 30 segundos..."
            sleep 30
          done
          echo "Erro na execução da coleta após 3 tentativas."
          exit 1

      - name: Retomar Monitoramento
        run: |
          echo "Retomando o monitoramento após a coleta..."
          curl -X GET http://198.58.120.71:8001/iniciar-monitoramento
          echo "Monitoramento retomado com sucesso."
